### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by olegabu** [olegabu/fabric-starter-admin-web#3]
- [x] Top left label should read not Hyperledger but the domain of the network, get it from the api at `/domain`.
- [x] Install chaincode should always show, no need to select channel to show it
- [x] Move Install chaincode section into the left column below Join channel
- [x] List all chaincodes installed in Install chaincode section
- [x] When no channel is selected don't show labels Chaincodes, Instantiate, Organizations, Targets
- [x] Replace Join the channel with Join channel
- [x] Remove (comment out for now) bottom bar with Web-admin label
- [x] Replace buttons Result, Info, Json with headers above each column: Transaction, Endorsed, Block
- [x] Transaction section should show a column of sections
 - Response: what the api returned (what you're showing now)
When the transaction commits, add these sections parsed out of the block just like in the 3rd column:
 - Input: args from ...chaincode_proposal_payload.input (convert each from Buffer into readable string)
 - Result: array of ns_rwset from ...proposal_response_payload.extension.results (show reads and writes)
- [x] Endorsed section should show a list of trnsaction creator and endorsers as their cert attributes
 - Creator subject.commonName issuer.organizationName
 - Endorser subject.commonName issuer.organizationName
 - Endorser subject.commonName issuer.organizationName
- [x] Replace Add Organization with Add Organization to Channel

**Comment by norikoff** [comment]
Fixed
